### ISSUE TITLE
Missing script file?

### ISSUE THREAD

**Issue by thestumbler** [tim-brown/shadesofamber#1]
Looks like the actual script file is missing from this repository?
In the meantime, I just downloaded it from vim.org
http://www.vim.org/scripts/script.php?script_id=3247

**Comment by tim-brown** [comment]
Thanks for letting me know. Will look into it.

Tim

On 15 August 2015 14:13:41 BST, Chris Lott notifications@github.com wrote:

> Looks like the actual script file is missing from this repository?
> In the meantime, I just downloaded it from vim.org
> http://www.vim.org/scripts/script.php?script_id=3247
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tim-brown/shadesofamber/issues/1

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tim-brown** [comment]
@thestumbler I ain’t half slow am I?
But there it is!

**Comment by thestumbler** [comment]
I'll bet I'm slower....
